# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
# baseURL = "https://your_domain.com/"
languageCode = "ja"
defaultContentLanguage = "ja"

[frontmatter]
# date = [":fileModTime"]
lastmod = [":git"]

[outputs]
home = ["HTML", "RSS", "JSON"]
