name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
    - work
    paths:
    - .github/workflows/deploy-portfolio.yml
    - archetypes/**
    - assets/**
    - config/**
    - content/**
    - themes/**

jobs:
  src-build-deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      TZ: Asia/Tokyo
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 0.128.2
    - name: Build Portfolio
      run: hugo --minify --environment production
    - name: Deploy Portfolio
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/work' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: deploy
        publish_dir: ./public
